pelvis_length: 0.282
com_height: 0.68
foot_radius: 0.05
control_period: 0.001

l_min: -0.50
l_max: 0.50

# w_min: -0.1
# w_max: 0.2
# t_min: 0.2
# t_max: 0.5
# t_nom: 0.3

w_min: -0.1
w_max: 0.3
t_min: 0.2
t_max: 0.5
t_nom: 0.2

cost_weights: [1, 1, 5, 1000, 1000, 100000, 100000, 100000, 100000]

swing_poly_traj:
  cost_x: 1e1
  cost_y: 1e1
  cost_z: 1e0
  hess_regul: 1e-6
  step_height: 0.1
